/**
 * Centralized es-MX UI strings. Single locale by design (no i18n lib in MVP);
 * keeping copy out of components makes future localization a data change,
 * not a refactor. Keys in English, values in Spanish (es-MX).
 */
export const copy = {
  common: {
    appName: 'Oficio',
    continue: 'Continuar',
    cancel: 'Cancelar',
    save: 'Guardar',
    retry: 'Reintentar',
    back: 'Atrás',
    loading: 'Cargando…',
    genericError: 'Algo salió mal. Intenta de nuevo.',
    offlineBanner: 'Sin conexión — mostrando información guardada',
    offlineQueued: 'Se enviará cuando vuelva la conexión',
  },
  auth: {
    welcomeTitle: 'Bienvenido a Oficio',
    welcomeSubtitle: 'Cotizaciones reales de prestadores verificados, sin llamadas ni regateos.',
    roleQuestion: '¿Cómo quieres usar Oficio?',
    roleClient: 'Necesito un servicio',
    roleClientDetail: 'Describe tu problema y recibe cotizaciones',
    roleProvider: 'Soy prestador de servicios',
    roleProviderDetail: 'Recibe solicitudes y envía cotizaciones profesionales',
    emailLabel: 'Correo electrónico',
    emailPlaceholder: 'tu@correo.com',
    emailInvalid: 'Ingresa un correo válido',
    sendCode: 'Enviar código',
    codeSentTitle: 'Revisa tu correo',
    codeSentBody: (email: string) => `Enviamos un código de 6 dígitos a ${email}`,
    codeLabel: 'Código de verificación',
    codeInvalid: 'El código debe tener 6 dígitos',
    verify: 'Verificar',
    resendCode: 'Reenviar código',
    orDivider: 'o continúa con',
    googleSignIn: 'Continuar con Google',
    appleSignIn: 'Continuar con Apple',
    signOut: 'Cerrar sesión',
    fullNameLabel: 'Nombre completo',
    fullNamePlaceholder: 'Como te conocen tus clientes',
    fullNameRequired: 'Ingresa tu nombre',
    completeProfileTitle: 'Completa tu perfil',
  },
  tabs: {
    client: {
      home: 'Inicio',
      requests: 'Solicitudes',
      jobs: 'Trabajos',
      profile: 'Perfil',
    },
    provider: {
      opportunities: 'Oportunidades',
      quotes: 'Cotizaciones',
      schedule: 'Agenda',
      business: 'Negocio',
      profile: 'Perfil',
    },
  },
  placeholders: {
    clientHome: 'Aquí crearás nuevas solicitudes y verás las activas.',
    clientRequests: 'Aquí verás tus solicitudes y compararás cotizaciones.',
    clientJobs: 'Aquí verás tus trabajos agendados, en curso e historial.',
    providerOpportunities: 'Aquí verás solicitudes de tu oficio y zona.',
    providerQuotes: 'Aquí armarás y darás seguimiento a tus cotizaciones.',
    providerSchedule: 'Aquí verás tu agenda de hoy y de la semana.',
    providerBusiness: 'Registro de ingresos y gastos (Premium).',
    profile: 'Tu información, privacidad y configuración de cuenta.',
    comingSoon: 'Disponible en la siguiente etapa',
  },
} as const;
