/**
 * Centralized es-MX UI strings. Single locale by design (no i18n lib in MVP);
 * keeping copy out of components makes future localization a data change,
 * not a refactor. Keys in English, values in Spanish (es-MX).
 */
export const copy = {
  common: {
    appName: 'Oficio',
    continue: 'Continuar',
    cancel: 'Cancelar',
    save: 'Guardar',
    saved: 'Cambios guardados',
    retry: 'Reintentar',
    back: 'Atrás',
    close: 'Cerrar',
    loading: 'Cargando…',
    genericError: 'Algo salió mal. Intenta de nuevo.',
    offlineBanner: 'Sin conexión — mostrando información guardada',
    offlineQueued: 'Se enviará cuando vuelva la conexión',
    seeAll: 'Ver todas',
    share: 'Compartir',
  },
  auth: {
    welcomeTitle: 'Bienvenido a Oficio',
    welcomeSubtitle: 'Cotizaciones reales de prestadores verificados, sin llamadas ni regateos.',
    roleQuestion: '¿Cómo quieres usar Oficio?',
    roleClient: 'Necesito un servicio',
    roleClientDetail: 'Describe tu problema y recibe cotizaciones',
    roleProvider: 'Soy prestador de servicios',
    roleProviderDetail: 'Recibe solicitudes y envía cotizaciones profesionales',
    emailLabel: 'Correo electrónico',
    emailPlaceholder: 'tu@correo.com',
    emailInvalid: 'Ingresa un correo válido',
    sendCode: 'Enviar código',
    codeSentTitle: 'Revisa tu correo',
    codeSentBody: (email: string) => 'Enviamos un código de 6 dígitos a ' + email,
    codeLabel: 'Código de verificación',
    codeInvalid: 'El código debe tener 6 dígitos',
    verify: 'Verificar',
    resendCode: 'Reenviar código',
    orDivider: 'o continúa con',
    googleSignIn: 'Continuar con Google',
    appleSignIn: 'Continuar con Apple',
    signOut: 'Cerrar sesión',
    fullNameLabel: 'Nombre completo',
    fullNamePlaceholder: 'Como te conocen tus clientes',
    fullNameRequired: 'Ingresa tu nombre',
    completeProfileTitle: 'Completa tu perfil',
    completeProfileSubtitle: 'Así te verán las personas con las que trabajes.',
    valueNoCalls: 'Sin llamadas ni regateos',
    valueWindows: 'Ventanas de llegada, no promesas',
    valueVerified: 'Prestadores verificados',
  },
  tabs: {
    client: {
      home: 'Inicio',
      requests: 'Solicitudes',
      jobs: 'Trabajos',
      profile: 'Perfil',
    },
    provider: {
      opportunities: 'Chambas',
      quotes: 'Cotizaciones',
      schedule: 'Agenda',
      business: 'Negocio',
      profile: 'Perfil',
    },
  },
  trades: {
    plumbing: 'Plomería',
    electrical: 'Electricidad',
    masonry: 'Albañilería',
    carpentry: 'Carpintería',
    cleaning: 'Limpieza',
    installations: 'Instalaciones',
  },
  urgency: {
    emergency: 'Emergencia',
    this_week: 'Esta semana',
    flexible: 'Flexible',
    emergencyHint: 'Hoy mismo, no puede esperar',
    thisWeekHint: 'En los próximos días',
    flexibleHint: 'Cuando haya disponibilidad',
  },
  visitType: {
    diagnostic: 'Diagnóstico',
    full_service: 'Servicio completo',
    diagnosticHint: 'No sé qué falla; quiero que lo revisen',
    fullServiceHint: 'Ya sé qué necesito que hagan',
  },
  requestStatus: {
    open: 'Abierta',
    quoted: 'Con cotizaciones',
    accepted: 'Aceptada',
    cancelled: 'Cancelada',
    expired: 'Vencida',
  },
  quoteStatus: {
    sent: 'Enviada',
    accepted: 'Aceptada',
    rejected: 'No elegida',
    expired: 'Vencida',
    withdrawn: 'Retirada',
  },
  jobStatus: {
    scheduled: 'Agendado',
    en_route: 'En camino',
    in_progress: 'En sitio',
    completed: 'Completado',
    cancelled: 'Cancelado',
  },
  clientHome: {
    greeting: (name: string) => 'Hola, ' + name.split(' ')[0],
    subtitle: '¿Qué necesitas resolver hoy?',
    newRequest: 'Nueva solicitud',
    newRequestHint: 'Describe el problema y recibe cotizaciones',
    quickTrades: 'Oficios',
    nextJob: 'Tu próxima visita',
    activeRequests: 'Solicitudes activas',
    noActiveRequests: 'No tienes solicitudes activas',
    noActiveRequestsBody: 'Cuando publiques una, aquí verás las cotizaciones que lleguen.',
    quotesWaiting: (count: number) =>
      count === 1 ? '1 cotización por revisar' : count + ' cotizaciones por revisar',
  },
  request: {
    listTitle: 'Mis solicitudes',
    active: 'Activas',
    history: 'Historial',
    emptyActive: 'Sin solicitudes activas',
    emptyActiveBody: 'Publica una solicitud y los prestadores de tu zona te cotizarán.',
    emptyHistory: 'Aún no hay historial',
    emptyHistoryBody: 'Las solicitudes cerradas o vencidas aparecerán aquí.',
    quotesCount: (count: number) =>
      count === 0 ? 'Sin cotizaciones aún' : count === 1 ? '1 cotización' : count + ' cotizaciones',
    detailTitle: 'Solicitud',
    photos: 'Fotos',
    address: 'Dirección',
    publishedAt: 'Publicada',
    quotesTitle: 'Cotizaciones recibidas',
    quotesEmpty: 'Todavía no llegan cotizaciones',
    quotesEmptyBody: 'Los prestadores de tu zona ya la están viendo. Suele tomar unas horas.',
    bestPrice: 'Precio más bajo',
    fastest: 'Más rápido',
    cancelRequest: 'Cancelar solicitud',
    cancelConfirm: '¿Cancelar esta solicitud? Los prestadores dejarán de verla.',
    cancelled: 'Solicitud cancelada',
  },
  newRequest: {
    title: 'Nueva solicitud',
    stepTrade: 'Oficio',
    stepDetails: 'Detalles',
    stepLocation: 'Ubicación',
    stepReview: 'Revisar',
    tradeQuestion: '¿Qué oficio necesitas?',
    visitQuestion: '¿Qué tipo de visita necesitas?',
    titleLabel: 'Título',
    titlePlaceholder: 'Fuga en el lavabo del baño',
    titleInvalid: 'Escribe un título de 4 a 120 caracteres',
    descriptionLabel: 'Descripción',
    descriptionPlaceholder:
      'Cuenta qué pasa, desde cuándo y qué has intentado. Entre más claro, mejores cotizaciones.',
    descriptionInvalid: 'Describe el problema con al menos 10 caracteres',
    photosLabel: 'Fotos del problema',
    photosHint: 'Una foto reduce a la mitad las preguntas de ida y vuelta.',
    addressLabel: 'Dirección',
    addressPlaceholder: 'Calle, número, colonia',
    addressInvalid: 'Ingresa la dirección del servicio',
    useMyLocation: 'Usar mi ubicación',
    locating: 'Obteniendo ubicación…',
    locationRequired: 'Necesitamos la ubicación para mostrar tu solicitud a prestadores cercanos',
    locationDenied: 'Activa el permiso de ubicación o escribe la dirección manualmente.',
    locationSet: 'Ubicación lista',
    urgencyQuestion: '¿Qué tan urgente es?',
    reviewTitle: 'Revisa antes de publicar',
    reviewHint: 'Tu dirección exacta solo se comparte con el prestador que elijas.',
    publish: 'Publicar solicitud',
    published: 'Solicitud publicada',
  },
  quote: {
    listTitle: 'Cotizaciones',
    sentTab: 'Enviadas',
    closedTab: 'Cerradas',
    emptySent: 'Sin cotizaciones enviadas',
    emptySentBody: 'Cuando cotices una oportunidad, aquí le das seguimiento.',
    emptyClosed: 'Nada cerrado todavía',
    emptyClosedBody: 'Aquí verás las cotizaciones aceptadas, vencidas o no elegidas.',
    builderTitle: 'Nueva cotización',
    conceptLabel: 'Concepto',
    conceptPlaceholder: 'Cambio de llave mezcladora',
    qtyLabel: 'Cant.',
    unitPriceLabel: 'Precio unitario',
    typeLabor: 'Mano de obra',
    typeMaterial: 'Material',
    addLine: 'Agregar concepto',
    removeLine: 'Quitar concepto',
    linesRequired: 'Agrega al menos un concepto con precio',
    subtotal: 'Subtotal',
    iva: 'IVA (16%)',
    total: 'Total',
    durationLabel: 'Duración estimada',
    durationInvalid: 'Entre 15 minutos y 48 horas',
    validityLabel: 'Vigencia',
    validityDays: (days: number) => (days === 1 ? '1 día' : days + ' días'),
    notesLabel: 'Notas para el cliente',
    notesPlaceholder: 'Qué incluye, qué no incluye, garantía.',
    send: 'Enviar cotización',
    sendSuccess: 'Cotización enviada',
    withdraw: 'Retirar cotización',
    withdrawConfirm: '¿Retirar esta cotización? El cliente dejará de verla.',
    validUntil: (date: string) => 'Vigente hasta ' + date,
    expiredNotice: 'Esta cotización ya venció',
    exportPdf: 'Compartir PDF',
    exportFailed: 'No se pudo generar el PDF',
    accept: 'Aceptar cotización',
    acceptTitle: 'Agenda la visita',
    acceptHint: 'Elige el día y la ventana de llegada acordada.',
    accepted: 'Cotización aceptada',
    alreadyQuoted: 'Ya cotizaste esta solicitud',
    durationValue: (minutes: number) =>
      minutes < 60
        ? minutes + ' min'
        : minutes % 60 === 0
          ? minutes / 60 + ' h'
          : Math.floor(minutes / 60) + ' h ' + (minutes % 60) + ' min',
  },
  schedule: {
    title: 'Agenda',
    today: 'Hoy',
    week: 'Semana',
    emptyToday: 'Sin visitas hoy',
    emptyTodayBody: 'Cotiza oportunidades para llenar tu agenda.',
    emptyWeek: 'Semana libre',
    emptyWeekBody: 'Los trabajos aceptados aparecerán aquí con su ventana de llegada.',
    markEnRoute: 'Voy en camino',
    markArrived: 'Llegué al sitio',
    markCompleted: 'Marcar completado',
    completionPhotos: 'Fotos del trabajo terminado',
    completionRequired: 'Agrega al menos una foto del trabajo terminado',
    cancelJob: 'Cancelar trabajo',
    cancelReasonLabel: 'Motivo de la cancelación',
    cancelReasonRequired: 'Escribe el motivo (mínimo 4 caracteres)',
    windowLabel: 'Ventana de llegada',
    arrivedAt: (time: string) => 'Llegada registrada ' + time,
  },
  job: {
    listTitle: 'Trabajos',
    upcoming: 'Próximos',
    history: 'Historial',
    emptyUpcoming: 'Sin trabajos agendados',
    emptyUpcomingBody: 'Cuando aceptes una cotización, la visita aparecerá aquí.',
    emptyHistory: 'Sin historial todavía',
    emptyHistoryBody: 'Los trabajos completados y cancelados se guardan aquí.',
    detailTitle: 'Trabajo',
    timeline: 'Seguimiento',
    provider: 'Prestador',
    client: 'Cliente',
    cancel: 'Cancelar visita',
    cancelConfirm: '¿Cancelar esta visita?',
    reviewCta: 'Calificar el trabajo',
    reviewDone: 'Ya calificaste este trabajo',
  },
  review: {
    title: 'Calificar trabajo',
    qualityLabel: 'Calidad del trabajo',
    punctualityLabel: 'Puntualidad',
    commentLabel: 'Comentario (opcional)',
    commentPlaceholder: '¿Qué salió bien? ¿Qué podría mejorar?',
    submit: 'Enviar calificación',
    submitted: 'Gracias por calificar',
    ratingRequired: 'Elige una calificación de 1 a 5',
  },
  opportunities: {
    title: 'Oportunidades',
    subtitle: (count: number) =>
      count === 1 ? '1 solicitud en tu zona' : count + ' solicitudes en tu zona',
    allTrades: 'Todos',
    empty: 'Sin solicitudes por ahora',
    emptyBody: 'Te avisaremos cuando llegue una de tu oficio en tu zona.',
    setupNeeded: 'Configura tu oficio y tu zona',
    setupBody: 'Sin oficios ni ubicación base no podemos mostrarte solicitudes cercanas.',
    setupCta: 'Configurar ahora',
    quoteCta: 'Cotizar',
    distance: (km: number) => 'a ' + km.toFixed(1) + ' km',
  },
  business: {
    title: 'Negocio',
    premiumTitle: 'Lleva tus números en orden',
    premiumBody:
      'El registro de ingresos y gastos es parte de Oficio Premium. Se activa desde el sitio web.',
    premiumNote: 'La suscripción no se vende dentro de la app.',
    income: 'Ingresos',
    expense: 'Gastos',
    balance: 'Balance',
    thisMonth: 'Este mes',
    addEntry: 'Registrar movimiento',
    entryType: 'Tipo',
    amountLabel: 'Monto',
    amountInvalid: 'Ingresa un monto mayor a cero',
    categoryLabel: 'Categoría',
    categoryPlaceholder: 'Material, gasolina, herramienta…',
    categoryInvalid: 'Escribe una categoría (2 a 60 caracteres)',
    empty: 'Sin movimientos este mes',
    emptyBody: 'Registra un ingreso o un gasto para empezar tu balance.',
  },
  profile: {
    title: 'Perfil',
    editTitle: 'Editar perfil',
    phoneLabel: 'Teléfono',
    phonePlaceholder: '55 1234 5678',
    phoneInvalid: 'Ingresa 10 dígitos',
    cityLabel: 'Ciudad',
    cityPlaceholder: 'Ciudad de México',
    coloniaLabel: 'Colonia',
    coloniaPlaceholder: 'Del Valle',
    account: 'Cuenta',
    memberSince: (date: string) => 'En Oficio desde ' + date,
    providerSetupTitle: 'Mi oficio y zona',
    tradesLabel: 'Oficios que ofreces',
    tradesRequired: 'Elige al menos un oficio',
    radiusLabel: 'Radio de servicio',
    radiusValue: (km: number) => km + ' km',
    baseLocationLabel: 'Ubicación base',
    baseLocationHint: 'Centro de tu zona de trabajo. Solo se usa para calcular distancias.',
    baseLocationMissing: 'Sin ubicación base',
    bioLabel: 'Sobre tu trabajo',
    bioPlaceholder: 'Años de experiencia, especialidad, garantía que ofreces.',
    metricsTitle: 'Tus indicadores',
    punctuality: 'Puntualidad',
    completion: 'Completados',
    responseTime: 'Respuesta',
    rating: 'Calificación',
    noMetrics: 'Aún sin datos',
    verification: {
      basic: 'Básico',
      verified: 'Verificado',
      premium: 'Premium',
    },
    reviewsTitle: 'Reseñas',
    reviewsEmpty: 'Sin reseñas todavía',
  },
  photos: {
    camera: 'Cámara',
    gallery: 'Galería',
    takePhoto: 'Tomar foto',
    fromLibrary: 'Elegir de la galería',
    remove: 'Quitar foto',
    permissionDenied: 'Necesitamos el permiso para agregar fotos.',
    hint: (used: number, max: number) => used + ' de ' + max + ' fotos',
    uploadFailed: 'No se pudieron subir las fotos',
  },
} as const;
