-- Photo storage. Two private buckets; reads go through short-lived signed URLs
-- generated by the client (lib/storage.ts). Private matters here: request
-- photos show the inside of someone's home, and a public bucket URL outlives
-- the request, the job and the block list.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('request-photos', 'request-photos', false, 8388608,
   array['image/jpeg', 'image/png', 'image/webp', 'image/heic']),
  ('job-photos', 'job-photos', false, 8388608,
   array['image/jpeg', 'image/png', 'image/webp', 'image/heic'])
on conflict (id) do nothing;

-- Objects are written under "<auth.uid()>/<file>" so ownership is the path
-- prefix — the same convention Supabase's own storage examples use.

create policy "request_photos_insert_own"
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'request-photos'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "request_photos_delete_own"
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'request-photos'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- Read is any signed-in user: a request is broadcast to every provider whose
-- trade and radius match, and that set is evaluated by the requests RLS policy,
-- not resolvable from a storage path. Paths are random, links expire in an
-- hour, and anon has no access at all.
create policy "request_photos_read_authenticated"
  on storage.objects for select to authenticated
  using (bucket_id = 'request-photos');

create policy "job_photos_insert_own"
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'job-photos'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "job_photos_delete_own"
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'job-photos'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "job_photos_read_authenticated"
  on storage.objects for select to authenticated
  using (bucket_id = 'job-photos');
